# Generated by Django 4.0.6 on 2022-08-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_tilte'),
    ]

    operations = [
        migrations.CreateModel(
            name='postsHide',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('tilte', models.TextField()),
            ],
        ),
    ]
